-- MySQL Script generated by MySQL Workbench
-- tis  9 feb 2021 18:56:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bultdatabasen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `resource_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resource_type` (
  `name` VARCHAR(64) NOT NULL,
  `depth` INT NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `index2` (`name` ASC, `depth` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resource` (
  `id` VARCHAR(36) NOT NULL,
  `type` VARCHAR(64) NOT NULL,
  `depth` INT NOT NULL,
  `name` VARCHAR(256) NULL,
  `parent_id` VARCHAR(36) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resource_1_idx` (`parent_id` ASC) VISIBLE,
  INDEX `fk_resource_2_idx` (`type` ASC, `depth` ASC) VISIBLE,
  CONSTRAINT `fk_resource_1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_2`
    FOREIGN KEY (`type` , `depth`)
    REFERENCES `resource_type` (`name` , `depth`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `route_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `route_type` (
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `installer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `installer` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `route` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `alt_name` VARCHAR(256) NULL,
  `year` INT NULL,
  `route_type` VARCHAR(64) NULL,
  `installer_id` VARCHAR(36) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_route_2_idx` (`route_type` ASC) VISIBLE,
  INDEX `fk_route_3_idx` (`installer_id` ASC) VISIBLE,
  CONSTRAINT `fk_route_1`
    FOREIGN KEY (`id`)
    REFERENCES `resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_2`
    FOREIGN KEY (`route_type`)
    REFERENCES `route_type` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_3`
    FOREIGN KEY (`installer_id`)
    REFERENCES `installer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `installation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `installation` (
  `id` VARCHAR(36) NOT NULL,
  `install_year` DATETIME NULL,
  `installer_id` VARCHAR(256) NULL,
  `type` ENUM('BOLT', 'ANCHOR') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_installation_1_idx` (`installer_id` ASC) VISIBLE,
  CONSTRAINT `fk_installation_1`
    FOREIGN KEY (`installer_id`)
    REFERENCES `installer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_installation_2`
    FOREIGN KEY (`id`)
    REFERENCES `resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `line_segment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `line_segment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `src_installation_id` VARCHAR(36) NOT NULL,
  `dst_installation_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_line_segment_1_idx` (`src_installation_id` ASC) VISIBLE,
  INDEX `fk_line_segment_2_idx` (`dst_installation_id` ASC) VISIBLE,
  CONSTRAINT `fk_line_segment_1`
    FOREIGN KEY (`src_installation_id`)
    REFERENCES `installation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_line_segment_2`
    FOREIGN KEY (`dst_installation_id`)
    REFERENCES `installation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `installation_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `installation_image` (
  `installation_id` VARCHAR(36) NOT NULL,
  `image_uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`installation_id`),
  CONSTRAINT `fk_installation_image_1`
    FOREIGN KEY (`installation_id`)
    REFERENCES `installation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` VARCHAR(36) NOT NULL,
  `email` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_team` (
  `user_id` VARCHAR(36) NOT NULL,
  `team_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`user_id`, `team_id`),
  INDEX `fk_user_team_2_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_team_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_team_2`
    FOREIGN KEY (`team_id`)
    REFERENCES `team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manufacturer` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component_type` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `component` (
  `id` VARCHAR(36) NOT NULL,
  `component_type_id` VARCHAR(36) NULL,
  `manufacturer_id` VARCHAR(36) NULL,
  `model` VARCHAR(256) NULL,
  `year_manufactured` TINYINT NULL,
  `batch_number` VARCHAR(256) NULL,
  `inherited_component_id` VARCHAR(36) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_component_2_idx` (`manufacturer_id` ASC) VISIBLE,
  INDEX `fk_component_3_idx` (`inherited_component_id` ASC) VISIBLE,
  INDEX `fk_component_1_idx` (`component_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_component_2`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `manufacturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_component_3`
    FOREIGN KEY (`inherited_component_id`)
    REFERENCES `component` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_component_1`
    FOREIGN KEY (`component_type_id`)
    REFERENCES `component_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `part`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `part` (
  `id` VARCHAR(36) NOT NULL,
  `installation_id` VARCHAR(36) NOT NULL,
  `orientation` ENUM('LEFT', 'RIGHT') NULL,
  `component_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_part_1_idx` (`installation_id` ASC) VISIBLE,
  INDEX `fk_part_2_idx` (`component_id` ASC) VISIBLE,
  CONSTRAINT `fk_part_1`
    FOREIGN KEY (`installation_id`)
    REFERENCES `installation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_part_2`
    FOREIGN KEY (`component_id`)
    REFERENCES `component` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role` (
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_role` (
  `user_id` VARCHAR(36) NOT NULL,
  `resource_id` VARCHAR(36) NOT NULL,
  `role` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`user_id`, `resource_id`),
  INDEX `fk_user_role_2_idx` (`resource_id` ASC) VISIBLE,
  INDEX `fk_user_role_3_idx` (`role` ASC) VISIBLE,
  CONSTRAINT `fk_user_role_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_2`
    FOREIGN KEY (`resource_id`)
    REFERENCES `resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_3`
    FOREIGN KEY (`role`)
    REFERENCES `role` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team_role` (
  `team_id` VARCHAR(36) NOT NULL,
  `resource_id` VARCHAR(36) NOT NULL,
  `role` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`team_id`, `resource_id`),
  INDEX `fk_team_role_2_idx` (`resource_id` ASC) VISIBLE,
  INDEX `fk_team_role_3_idx` (`role` ASC) VISIBLE,
  CONSTRAINT `fk_team_role_1`
    FOREIGN KEY (`team_id`)
    REFERENCES `team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_role_2`
    FOREIGN KEY (`resource_id`)
    REFERENCES `resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_role_3`
    FOREIGN KEY (`role`)
    REFERENCES `role` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `installation_route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `installation_route` (
  `installation_id` VARCHAR(36) NOT NULL,
  `route_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`installation_id`, `route_id`),
  INDEX `fk_installation_route_2_idx` (`route_id` ASC) VISIBLE,
  CONSTRAINT `fk_installation_route_1`
    FOREIGN KEY (`installation_id`)
    REFERENCES `installation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_installation_route_2`
    FOREIGN KEY (`route_id`)
    REFERENCES `route` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
