environment:
  SPACES_KEY: "${SPACES_KEY}"
  SPACES_SECRET: "${SPACES_SECRET}"
  SECRET: "letmein"
parameters: {}
packages:
  - name: images
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: resize
        binary: false
        main: ""
        runtime: "python:default"
        web: true
        parameters: {}
        environment: {}
        annotations:
          webSecure: letmein
        limits:
          timeout: 10000
          memory: 1024
