environment: {}
parameters: {}
packages:
  - name: images
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: resize
        binary: false
        main: ""
        runtime: "python:default"
        web: true
        webSecure: "${FUNCTIONS_SECRET}"
        parameters: {}
        environment: {}
        annotations: {}
        limits:
          timeout: 10000
          memory: 1024
