jobs:
  build:
    name: Deploy
    runs-on: ubuntu-20.04
    environment: production

    steps:
      - uses: actions/checkout@v3
      - run: cp backend/keys/production.json packageroot/etc/bultdatabasen/keys.json
      - uses: ./.github/actions/build
      - name: Upload sourcemap
        env:
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
        run: |
          pnpm install @sentry/cli --save-dev
          ./node_modules/.bin/sentry-cli login --auth-token "${SENTRY_TOKEN}"
          ./node_modules/.bin/sentry-cli releases new "bultdatabasen@${GITHUB_RUN_ID}" --org bultdatabasen --project bultdatabasen
          ./node_modules/.bin/sentry-cli releases files "bultdatabasen@${GITHUB_RUN_ID}" upload-sourcemaps --ext map dist/assets --org bultdatabasen --project bultdatabasen
        working-directory: web

  build-function:
    name: Deploy Function
    runs-on: ubuntu-20.04
    environment: production

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-function
        with:
          namespace: production
          secret: ${{ secrets.FUNCTIONS_SECRET }}
          token: ${{ secrets.DO_API_TOKEN }}

on:
  push:
    branches:
      - develop
  release:
    types: [published]
