jobs:
  build:
    name: Deploy Function
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install and Configure doctl
        run: |
          wget https://github.com/digitalocean/doctl/releases/download/v1.86.0/doctl-1.86.0-linux-amd64.tar.gz
          tar xf doctl-1.86.0-linux-amd64.tar.gz
          sudo mv doctl /usr/local/bin
          doctl auth init --verbose --access-token=${{ secrets.DO_API_TOKEN }}
          doctl serverless install
      - name: Deploy
        env:
          SPACES_SECRET: ${{ secrets.SPACES_SECRET }}
          SPACES_KEY: ${{ secrets.SPACES_KEY }}
          SECRET: "letmein"
        run: |
          doctl serverless connect sandbox
          doctl serverless deploy .
        working-directory: backend/functions

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - 245-create-github-workflow-to-deploy-image-resize-function-to-do
    paths:
      - "backend/functions/**"
      - ".github/workflows/deploy-function.yml"
