jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/setup-go@v2
        with:
          go-version: "1.19"
          check-latest: true
      - name: Build app
        run: |
          npm install
          npm run build
        working-directory: web
      - name: Build backend
        run: |
          go build
        working-directory: backend
      - name: Build package archive
        run: |
          mkdir -p packageroot/var/lib/bultdatabasen/images
          mkdir -p packageroot/usr/share/bultdatabasen
          mkdir -p packageroot/usr/bin
          mv web/dist packageroot/usr/share/bultdatabasen/
          mv backend/bultdatabasen packageroot/usr/bin
          sed -i "s/VERSION/${GITHUB_RUN_ID}/g" packageroot/DEBIAN/control
          dpkg-deb -b packageroot .
      - name: Upload archive
        uses: actions/upload-artifact@v3
        with:
          path: bultdatabasen_*_amd64.deb

on:
  push:
    branches:
      - develop
  release:
    types: [published]
