jobs:
  build:
    name: Deploy
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: ../actions/build.yml
      - name: Upload sourcemap
        env:
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
        run: |
          npm install @sentry/cli --save-dev
          ./node_modules/.bin/sentry-cli login --auth-token "${SENTRY_TOKEN}"
          ./node_modules/.bin/sentry-cli releases new "bultdatabasen@${GITHUB_RUN_ID}" --org bultdatabasen --project bultdatabasen
          ./node_modules/.bin/sentry-cli releases files "bultdatabasen@${GITHUB_RUN_ID}" upload-sourcemaps --ext map dist/assets --org bultdatabasen --project bultdatabasen
        working-directory: web

on:
  push:
    branches:
      - develop
  release:
    types: [published]
