jobs:
  build:
    name: Pull Request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
          check-latest: true
      - name: Install dependencies
        run: |
          npm install
        working-directory: web
      - name: Lint app
        run: |
          npm run lint
        working-directory: web
      - name: Build app
        run: |
          npm run build
        working-directory: web
      - name: Build backend
        run: |
          go build
        working-directory: backend

on: pull_request
