jobs:
  app:
    name: Build app
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: |
          git grep -l "bultdatabasen.se" | xargs sed -i 's/bultdatabasen.se/test.bultdatabasen.se/g'
      - name: Install dependencies
        run: |
          npm install
        working-directory: web
      - name: Lint app
        run: |
          npm run lint
        working-directory: web
      - name: Build app
        run: |
          npm run build
        working-directory: web

  backend:
    name: Build backend
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          check-latest: true
      - run: |
          git grep -l "bultdatabasen.se" | xargs sed -i 's/bultdatabasen.se/test.bultdatabasen.se/g'
      - name: Lint backend
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
          working-directory: backend
          args: --issues-exit-code=0
      - name: Build backend
        run: |
          go build -ldflags="-X 'main.Version=${GITHUB_RUN_ID}'"
        working-directory: backend

on: pull_request
