jobs:
  lint-app:
    name: Lint app
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.3
      - name: Install dependencies
        run: |
          pnpm install
        working-directory: web
      - name: Lint app
        run: |
          pnpm lint
        working-directory: web

  lint-backend:
    name: Lint backend
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
      - name: Lint backend
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
          working-directory: backend
          args: --issues-exit-code=0

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: [lint-app, lint-backend]
    environment: test

    steps:
      - uses: actions/checkout@v3
      - run: |
          for f in "web/src/config.json" "backend/cors.go" "backend/usecases/new_task.tmpl" "packageroot/etc/nginx/sites-available/api.bultdatabasen.se" "packageroot/etc/nginx/sites-available/bultdatabasen.se"; do
            sed -i 's/bultdatabasen.se/test.bultdatabasen.se/g' $f
          done
          sudo apt install -y jq
          echo $(jq '.COGNITO_URL = "https://bultdatabasen-test.auth.eu-west-1.amazoncognito.com" | .COGNITO_CLIENT_ID = "2lnodlocb4poce8o3rlut10gl2" | .COGNITO_POOL_ID = "eu-west-1_d1eMD1FK1"' web/src/config.json) > web/src/config.json
      - run: cp backend/keys/test.json packageroot/etc/bultdatabasen/keys.json
      - uses: ./.github/actions/build

  build-function:
    name: Deploy Function
    runs-on: ubuntu-20.04
    environment: test

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-function
        with:
          namespace: test
          secret: ${{ secrets.FUNCTIONS_SECRET }}
          token: ${{ secrets.DO_API_TOKEN }}

on: pull_request
