jobs:
  build:
    name: Pull Request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Build app
        run: |
          npm install
          npm run build
        working-directory: web
      - name: Build backend
        run: |
          go build
        working-directory: backend

on:
  pull_request:
    types: [ready_for_review]
