jobs:
  app:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          npm install
        working-directory: web
      - name: Lint app
        run: |
          npm run lint
        working-directory: web
      - name: Build app
        run: |
          sed -i -E "s/(\"version\": )\".+\"/\1\"${GITHUB_RUN_ID}\"/" package.json
          npm run build
          npm install @sentry/cli --save-dev
          ./node_modules/.bin/sentry-cli login --auth-token "${SENTRY_TOKEN}"
          ./node_modules/.bin/sentry-cli releases new "bultdatabasen@${GITHUB_RUN_ID}" --org bultdatabasen --project javascript-react
          ./node_modules/.bin/sentry-cli releases files "bultdatabasen@${GITHUB_RUN_ID}" upload-sourcemaps --ext map dist/assets --org bultdatabasen --project javascript-react
        working-directory: web

  backend:
    name: Build backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.19"
          check-latest: true
      - name: Lint backend
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
          working-directory: backend
          args: --issues-exit-code=0
      - name: Build backend
        run: |
          go build
        working-directory: backend

on: pull_request
